apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alpha-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/henrsand/argolab
    targetRevision: main
    path: pipelines/alpha-pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-tasks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
